[package]
name = "rust_playstation_emulator"
version = "0.1.0"
authors = ["Jack <admin@deadcore.co.uk>"]
edition = "2018"

[dependencies]
log = "^0.4"
env_logger = "^0.6"
prettytable-rs = "^0.8"

[lib]
name = "rust_playstation_emulator"
path = "src/lib.rs"

[[bin]]
name = "rust_playstation_emulator"
path = "src/bin/emulator.rs"